<?php
/**
 * Language labels for extension 'kb_shop'
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'pi1_title' => 'Shop (Cached)',	
		'pi2_title' => 'Shop (Uncached)',	
		'pi1_plus_wiz_description' => 'Implements a webshop (Use this version for the static pages of the shop. You can make a link to the dynamic version which get\'s used for searching.)',	
		'pi2_plus_wiz_description' => 'Implements a webshop (This version is not cached and get used to perform searches and deliver the results.)',	
		'pi1.subconf' => 'Sub-Configuration',
		'pi1.pages' => 'Product Folders',
		'pi1.pages_recursive' => 'Product Folders recursive',
		'pi1.pages_recursive.no' => 'No recursion',
		'pi1.pages_recursive.1level' => 'One level',
		'pi1.pages_recursive.2level' => 'Two levels',
		'pi1.pages_recursive.3level' => 'Three levels',
		'pi1.pages_recursive.infinite' => 'Infinite',
		'pi1.template' => 'Template File',
		'pi1.disableSingleView' => 'Disable Single-View',
		'pi1.sheet_listView.disableListView' => 'Disable List-View',
		'pi1.table' => 'Displayed Table',
		'pi1.sheet_search' => 'Search',
		'pi1.sheet_forms' => 'Forms',
		'pi1.sheet_forms.field_formcode' => 'Form Code',
		'pi1.sheet_forms.list_forms_section.list_form_item' => 'Form table',
		'pi1.sheet_forms.list_forms_section.list_form_item.form_name' => 'Form name',
		'pi1.sheet_forms.list_fieldmapping_section.list_fieldmapping_item' => 'Field mapping',
		'pi1.sheet_forms.list_fieldmapping_section.list_fieldmapping_item.field_source' => 'Source field',
		'pi1.sheet_forms.list_fieldmapping_section.list_fieldmapping_item.field_target' => 'Target field',
		'pi1.sheet_forms.list_fieldmapping_section.list_fieldmapping_item.field_transferts' => 'Transfer TS',
		'pi1.sheet_search.search_page' => 'Search page',
		'pi1.sheet_search.show_searchbox' => 'Show search-box',
		'pi1.sheet_search.list_searchfield_section.list_searchfield_item' => 'Searched field',
		'pi1.sheet_search.list_searchfield_section.field_searchfield_field' => 'Field',
		'pi1.sheet_listView' => 'List view',
		'pi1.sheet_listView.itemsPerPage' => 'Items per page',
		'pi1.sheet_listView.showPagebrowser' => 'Show page browser',
		'pi1.sheet_listView.pagesInBrowser' => 'Pages in browser',
		'pi1.sheet_listView.showFirstLast' => 'Show first and last link',
		'pi1.sheet_listView.showPrevNext' => 'Show previous and next link',
		'pi1.sheet_listView.list_order_section.list_order_item' => 'Order Item',
		'pi1.sheet_listView.list_order_section.list_order_item.field_list_order' => 'Order field',
		'pi1.sheet_listView.list_order_section.list_order_item.field_list_direction' => 'Order direction',
		'pi1.sheet_listView.list_order_section.list_order_item.field_order_custom' => 'Custom order',
		'pi1.sheet_listView.list_order_section.list_order_item.field_order_user' => 'User selectable',
		'direction.ascending' => 'Ascending',
		'direction.descending' => 'Descending',
		'pi1.sheet_singleView' => 'Detail view',
		'pi1.sheet_criteria' => 'Criteria',
		'pi1.sheet_criteria.show_criteria_selector' => 'Show criteria-selector',
		'pi1.sheet_criteria.wait4submit' => 'Wait for submit',
		'pi1.sheet_criteria.list_criteria_section.list_criteria_item' => 'Criteria item',
		'pi1.sheet_criteria.list_criteria_section.list_subcriteria' => 'Sub-Criteria item',
		'pi1.sheet_criteria.list_criteria_section.field_compare_field' => 'Field',
		'pi1.sheet_criteria.list_criteria_section.field_compare_custom' => 'Custom compare',
		'pi1.sheet_criteria.list_criteria_section.field_compare_dateoffset' => 'Offset (in h)',
		'pi1.sheet_criteria.list_criteria_section.field_compare_usersel' => 'User selectable',
		'pi1.sheet_criteria.list_criteria_section.field_compare_value' => 'Value',
		'pi1.sheet_criteria.list_criteria_section.field_compare_value_custom' => 'TS Obj-Path',
		'pi1.sheet_criteria.list_criteria_section.field_compare_list' => 'Compare lists',
		'pi1.sheet_criteria.list_criteria_section.field_compare_list.in_list' => 'In list',
		'pi1.sheet_criteria.list_criteria_section.field_compare_number' => 'Compare numbers',
		'pi1.sheet_criteria.list_criteria_section.field_compare_number.smaller' => 'Smaller',
		'pi1.sheet_criteria.list_criteria_section.field_compare_number.bigger' => 'Bigger',
		'pi1.sheet_criteria.list_criteria_section.field_compare_number.equals' => 'Equals',
		'pi1.sheet_criteria.list_criteria_section.field_compare_number.in' => 'One of',
		'pi1.sheet_criteria.list_criteria_section.field_compare_date' => 'Compare dates',
		'pi1.sheet_criteria.list_criteria_section.field_compare_date.before' => 'Before',
		'pi1.sheet_criteria.list_criteria_section.field_compare_date.after' => 'After',
		'pi1.sheet_criteria.list_criteria_section.field_compare_date.beforeNow' => 'Before now',
		'pi1.sheet_criteria.list_criteria_section.field_compare_date.afterNow' => 'After now',
		'pi1.sheet_criteria.list_criteria_section.field_compare_date.at' => 'At',
		'pi1.sheet_criteria.list_criteria_section.field_compare_boolean' => 'Value set',
		'pi1.sheet_criteria.list_criteria_section.field_compare_string' => 'Compare string',
		'pi1.sheet_criteria.list_criteria_section.field_compare_string.like' => 'Like',
		'pi1.sheet_criteria.list_criteria_section.field_compare_string.begins_with' => 'Begins with',
		'pi1.sheet_criteria.list_criteria_section.field_compare_string.ends_with' => 'Ends with',
		'pi1.sheet_criteria.list_criteria_section.field_compare_string.contains' => 'Contains',
		'pi1.sheet_criteria.list_criteria_section.field_compare_string.equals' => 'Equals',
		'pi1.sheet_criteria.list_criteria_section.field_compare_rendercheck_multibool' => 'Render as Checkboxes',
		'pi1.sheet_criteria.list_criteria_section.field_compare_negate' => 'Negate compare results',
		'pi1.sheet_criteria.list_criteria_section.field_compare_defaultNone' => 'Defaultselection "None"',
		'pi1.sheet_criteria.criteriaConnector' => 'Criteria Connector',
		'criteriaConnector.AND' => 'AND',
		'criteriaConnector.OR' => 'OR',
		'pi1.sheet_forms.list_forms_section.list_form_item' => 'Form item',
		'pi1.sheet_forms.list_forms_section.list_form_item.form_table' => 'Form table',
		'pi1.sheet_forms.list_forms_section.list_form_item.save_table' => 'Save table',
		'pi1.sheet_forms.submitTarget' => 'Submit Target on OK',
		'field._custom' => 'Custom (by TS)',
		'field.sorting' => 'Sorting',
		'field.uid' => 'Item UID',
		'field.pid' => 'Product folder',
		'field.crdate' => 'Creation date',
		'field.tstamp' => 'Modification date',
		'field.cruser_id' => 'Created by',
		'field.deleted' => 'Deleted',
		'field.hidden' => 'Hidden',
		'field.starttime' => 'Starttime',
		'field.endtime' => 'Endtime',
		'field.fe_group' => 'Benutzergruppe',
		'field.title' => 'Title',
		'field.category' => 'Category',
		'label.delete' => 'Do you really want to delete this section item ?',
		'isEmail.incorrect_at_dot' => 'Email address seems incorrect (check @ and .\'s) !',
		'isEmail.username_chars' => 'The username contains invalid characters !',
		'isEmail.domain_chars' => 'The domain name contains invalid characters !',
		'isEmail.username_invalid' => 'The username doesn\'t seem to be valid !',
		'isEmail.destip_invalid' => 'Destination IP address is invalid !',
		'isEmail.domain_invalid' => 'The domain name does not seem to be valid !',
		'isEmail.domain_tld' => 'The address must end in a well-known domain or two letter country !',
		'isEmail.host_missing' => 'This address is missing a hostname !',
	),
	'dk' => Array (
	),
	'de' => Array (
		'pi1_title' => 'Shop (Gecached)',	
		'pi2_title' => 'Shop (Nicht gecached)',	
		'pi1_plus_wiz_description' => 'Ein web-shop (Verwenden sie diese Version für statische Seiten des Shops. Sie können einen Link zur dynamischen Version die z.B. zum Suchen verwendet wird erstellen.)',	
		'pi2_plus_wiz_description' => 'Ein web-shop (Diese Version ist nicht gecached und kann für Suchabfragen udgl. verwendet werden.)',	
		'pi1.subconf' => 'Sub-Konfiguration',
		'pi1.pages' => 'Produkt Ordner',
		'pi1.pages_recursive' => 'Produkt Ordner rekursiv',
		'pi1.pages_recursive.no' => 'Keine Rekursion',
		'pi1.pages_recursive.1level' => 'Ein Level',
		'pi1.pages_recursive.2level' => 'Zwei Levels',
		'pi1.pages_recursive.3level' => 'Drei Level',
		'pi1.table' => 'Angezeigte Tabelle',
		'pi1.sheet_criteria.list_criteria_section.field_compare_rendercheck_multibool' => 'Als Ankreuzfeld darstellen',
		'pi1.pages_recursive.infinite' => 'Unendlich',
		'pi1.sheet_criteria.list_criteria_section.list_criteria_item' => 'Kriterium',
		'pi1.sheet_criteria.list_criteria_section.list_subcriteria' => 'Sub-Kriterium',
		'pi1.sheet_criteria.list_criteria_section.field_compare_field' => 'Feld',
		'pi1.sheet_criteria.list_criteria_section.field_compare_custom' => 'Benutzerdefnierter Vergleich',
		'pi1.sheet_criteria.list_criteria_section.field_compare_dateoffset' => 'Unterschied (in h)',
		'pi1.sheet_criteria.list_criteria_section.field_compare_usersel' => 'Vom Besucher auswählbar',
		'pi1.sheet_criteria.list_criteria_section.field_compare_value' => 'Wert',
		'pi1.sheet_criteria.list_criteria_section.field_compare_list' => 'Vergleichs Liste',
		'pi1.sheet_criteria.list_criteria_section.field_compare_list.in_list' => 'In der Liste',
		'pi1.sheet_criteria.list_criteria_section.field_compare_number' => 'Vergleichs Zahl',
		'pi1.sheet_criteria.list_criteria_section.field_compare_number.smaller' => 'Kleiner',
		'pi1.sheet_criteria.list_criteria_section.field_compare_number.bigger' => 'Grösser',
		'pi1.sheet_criteria.list_criteria_section.field_compare_number.equals' => 'Gleich',
		'pi1.sheet_criteria.list_criteria_section.field_compare_date' => 'Vergleichs Datum',
		'pi1.sheet_criteria.list_criteria_section.field_compare_date.before' => 'Bevor',
		'pi1.sheet_criteria.list_criteria_section.field_compare_date.after' => 'Nach',
		'pi1.sheet_criteria.list_criteria_section.field_compare_date.beforeNow' => 'Bevor jetzt',
		'pi1.sheet_criteria.list_criteria_section.field_compare_date.afterNow' => 'Nach jetzt',
		'pi1.sheet_criteria.list_criteria_section.field_compare_date.at' => 'Um',
		'pi1.sheet_criteria.list_criteria_section.field_compare_boolean' => 'Wert gesetzt',
		'pi1.sheet_criteria.list_criteria_section.field_compare_string' => 'Vergleichs Zeichenkette',
		'pi1.sheet_criteria.list_criteria_section.field_compare_string.like' => 'Wie (LIKE)',
		'pi1.sheet_criteria.list_criteria_section.field_compare_string.begins_with' => 'Beginnt mit',
		'pi1.sheet_criteria.list_criteria_section.field_compare_string.ends_with' => 'Endet mit',
		'pi1.sheet_criteria.list_criteria_section.field_compare_string.contains' => 'Beinhaltet',
		'pi1.sheet_criteria.list_criteria_section.field_compare_string.equals' => 'Ist gleich',
		'pi1.sheet_criteria.list_criteria_section.field_compare_negate' => 'Invertiere Ergebnis',
		'pi1.sheet_criteria.list_criteria_section.field_compare_defaultNone' => 'Standaradauswahl "Keine"',
		'pi1.sheet_criteria.criteriaConnector' => 'Kriterien Verbindung',
		'criteriaConnector.AND' => 'UND',
		'criteriaConnector.OR' => 'ODER',
		'pi1.sheet_listView' => 'Listenansicht',
		'pi1.sheet_listView.itemsPerPage' => 'Elemente pro Seite',
		'pi1.sheet_listView.showPagebrowser' => 'Zeige Seiten Browser',
		'pi1.sheet_listView.pagesInBrowser' => 'Anzahl Seiten in Browser',
		'pi1.sheet_listView.showFirstLast' => 'Zeige "erstes" und "letztes" Link',
		'pi1.sheet_listView.showPrevNext' => 'Zeige "vorheriges" und "nächstes" Link',
		'pi1.sheet_listView.list_order_section.list_order_item' => 'Sortier Wert',
		'pi1.sheet_listView.list_order_section.list_order_item.field_list_order' => 'Sortier Feld',
		'pi1.sheet_listView.list_order_section.list_order_item.field_list_direction' => 'Sortier Richtung',
		'pi1.sheet_listView.list_order_section.list_order_item.field_order_custom' => 'Spezielle Sortierung',
		'pi1.sheet_listView.list_order_section.list_order_item.field_order_user' => 'Vom Benutzer auswählbar',
		'isEmail.incorrect_at_dot' => 'Email Adresse ist falsch (überprüfen Sie @ und .) !',
		'isEmail.username_chars' => 'Der Benutzer beinhaltet ungültige Zeichen !',
		'isEmail.domain_chars' => 'Der Domain Name beinhaltet ungültige Zeichen !',
		'isEmail.username_invalid' => 'Der Benutzer Name ist nicht gültig !',
		'isEmail.destip_invalid' => 'Ziel IP ist ungültig !',
		'isEmail.domain_invalid' => 'Der Domain Name ist nicht gültig !',
		'isEmail.domain_tld' => 'Die E-Mail Adresse muss mit einer bekannten Domain oder einer 2-Zeichen Domain enden !',
		'isEmail.host_missing' => 'Der E-Mail Adresse fehlt ein Hostname !',
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>
